// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Readex_Pro } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });



// const readexPro = Readex_Pro({
//   subsets: ["latin"],
//   variable: "--font-readex-pro",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${readexPro.variable} font-gabriola antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Readex_Pro,Nanum_Myeongjo  } from "next/font/google";
// import localFont from "next/font/local";

// import "./globals.css";

// const geistSans = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// const gabriola = localFont({
//   src: "../public/fonts/Gabriola.ttf",
//   variable: "--font-gabriola",
// });

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
// });

// const readexPro = Readex_Pro({
//   subsets: ["latin"],
//   weight: ["400"],
//   variable: "--font-readex",
// });
// const nanumMyeongjo = Nanum_Myeongjo({
//   subsets: ["latin"],
//   weight: ["400"],
//   variable: "--font-nanum",
// });


// export const metadata: Metadata = {
//   title: "SareeWeb",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`
//           ${geistSans.variable}
//           ${geistMono.variable}
//           ${readexPro.variable}
//            ${nanumMyeongjo.variable}
//            ${gabriola.variable}
//           antialiased
//         `}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


  // import type { Metadata } from "next";
  // import { Geist, Geist_Mono, Readex_Pro, Nanum_Myeongjo } from "next/font/google";

  // import "./globals.css";

  // const geistSans = Geist({
  //   subsets: ["latin"],
  //   variable: "--font-geist-sans",
  // });

  // const geistMono = Geist_Mono({
  //   subsets: ["latin"],
  //   variable: "--font-geist-mono",
  // });

  // const readexPro = Readex_Pro({
  //   subsets: ["latin"],
  //   variable: "--font-readex",
  // });

  // const nanumMyeongjo = Nanum_Myeongjo({
  //   subsets: ["latin"],
  //   weight: ["400"],
  //   variable: "--font-nanum",
  // });



  // export const metadata: Metadata = {
  //   title: "SareeWeb",
  //   description: "Generated by create next app",
  // };

  // export default function RootLayout({
  //   children,
  // }: {
  //   children: React.ReactNode;
  // }) {
  //   return (
  //     <html lang="en">
  //       <body
  //         className={`
  //           ${geistSans.variable}
  //           ${geistMono.variable}
  //           ${readexPro.variable}
  //           ${nanumMyeongjo.variable}
          
  //           antialiased
  //         `}
  //       >
  //         {children}
  //       </body>
  //     </html>
  //   );
  // }
import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Readex_Pro,
  Nanum_Myeongjo,
   Cormorant_Garamond,
} from "next/font/google";
import "./globals.css";

/* Fonts */
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const readexPro = Readex_Pro({
  subsets: ["latin"],
  variable: "--font-readex",
});
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant",
  display: "swap",
});

const nanumMyeongjo = Nanum_Myeongjo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-nanum",
});

/* SEO METADATA */
export const metadata: Metadata = {
  metadataBase: new URL("https://houseofpriya.vercel.app"),

  title: {
    default: "House of Priya | Premium Sarees Online",
    template: "%s | House of Priya",
  },

  description:
    "House of Priya offers premium silk, cotton and designer sarees online. Elegant collections with all over India delivery.",

  keywords: [
    "house of priya",
    "sarees online",
    "premium sarees",
    "silk sarees",
    "designer sarees",
    "wedding sarees",
    "cotton sarees",
    "indian sarees",
  ],

  authors: [{ name: "House of Priya" }],
  creator: "House of Priya",
  publisher: "House of Priya",

  robots: {
    index: true,
    follow: true,
  },

  openGraph: {
    title: "House of Priya | Premium Sarees Online",
    description:
      "Discover premium silk & designer sarees at House of Priya. Shop elegant sarees online.",
    url: "https://houseofpriya.vercel.app",
    siteName: "House of Priya",
    images: [
      {
        url: "https://houseofpriya.vercel.app/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "House of Priya Premium Sarees",
      },
    ],
    locale: "en_IN",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "House of Priya | Premium Sarees Online",
    description:
      "Shop premium silk, cotton & designer sarees online at House of Priya.",
    images: ["https://houseofpriya.vercel.app/og-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Store",
              name: "House of Priya",
              url: "https://houseofpriya.vercel.app",
              logo: "https://houseofpriya.vercel.app/logo.png",
              sameAs: [
                "https://www.instagram.com/notdummy/?hl=en",
              ],
              address: {
                "@type": "PostalAddress",
                addressCountry: "IN",
              },
            }),
          }}
        />
      </head>

      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${readexPro.variable}
          ${nanumMyeongjo.variable}
          ${cormorant.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
