// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Readex_Pro } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });



// const readexPro = Readex_Pro({
//   subsets: ["latin"],
//   variable: "--font-readex-pro",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${readexPro.variable} font-gabriola antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Readex_Pro,Nanum_Myeongjo  } from "next/font/google";
// import localFont from "next/font/local";

// import "./globals.css";

// const geistSans = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// const gabriola = localFont({
//   src: "../public/fonts/Gabriola.ttf",
//   variable: "--font-gabriola",
// });

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
// });

// const readexPro = Readex_Pro({
//   subsets: ["latin"],
//   weight: ["400"],
//   variable: "--font-readex",
// });
// const nanumMyeongjo = Nanum_Myeongjo({
//   subsets: ["latin"],
//   weight: ["400"],
//   variable: "--font-nanum",
// });


// export const metadata: Metadata = {
//   title: "SareeWeb",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`
//           ${geistSans.variable}
//           ${geistMono.variable}
//           ${readexPro.variable}
//            ${nanumMyeongjo.variable}
//            ${gabriola.variable}
//           antialiased
//         `}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono, Readex_Pro, Nanum_Myeongjo } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const readexPro = Readex_Pro({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-readex",
});

const nanumMyeongjo = Nanum_Myeongjo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-nanum",
});



export const metadata: Metadata = {
  title: "SareeWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${readexPro.variable}
          ${nanumMyeongjo.variable}
         
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
